package com.pujoroute.wear.data

import android.content.Context
import kotlinx.serialization.json.Json

/** Parses the bundled JSON assets (generated by wear/tools/generate_assets.py). Pure JVM, unit-testable. */
object PujoParser {
    private val json = Json { ignoreUnknownKeys = true }

    fun calendar(text: String): CalendarData = json.decodeFromString(CalendarData.serializer(), text)
    fun pandals(text: String): List<Pandal> =
        json.decodeFromString(kotlinx.serialization.builtins.ListSerializer(Pandal.serializer()), text)
    fun emergency(text: String): EmergencyData = json.decodeFromString(EmergencyData.serializer(), text)
    fun metro(text: String): MetroData = json.decodeFromString(MetroData.serializer(), text)

    /** Case-insensitive search over name, landmark, metro station and area. */
    fun search(pandals: List<Pandal>, query: String, limit: Int = 50): List<Pandal> {
        val terms = query.lowercase().split(Regex("\\s+")).filter { it.isNotBlank() }
        if (terms.isEmpty()) return emptyList()
        return pandals.asSequence()
            .filter { p ->
                val hay = "${p.name} ${p.landmark} ${p.metro} ${p.area} ${p.zone}".lowercase()
                terms.all { it in hay }
            }
            .sortedWith(compareBy<Pandal>({ !it.name.lowercase().contains(terms.first()) }, { it.rank }, { it.name }))
            .take(limit)
            .toList()
    }

    /** Zones in a stable, human-friendly order, then any others alphabetically. */
    private val zoneOrder = listOf("North", "Central", "South", "Salt Lake")

    fun groupByZone(pandals: List<Pandal>): List<Pair<String, List<Pandal>>> =
        pandals.groupBy { it.zone }
            .mapValues { (_, list) -> list.sortedWith(compareBy<Pandal>({ it.rank }, { it.name.lowercase() })) }
            .toList()
            .sortedWith(compareBy<Pair<String, List<Pandal>>> {
                zoneOrder.indexOf(it.first).let { i -> if (i < 0) Int.MAX_VALUE else i }
            }.thenBy { it.first })
}

/** Lazily loaded, process-wide data (assets are read once). */
class PujoRepository private constructor(context: Context) {
    private val assets = context.applicationContext.assets
    private fun read(name: String) = assets.open(name).bufferedReader(Charsets.UTF_8).use { it.readText() }

    val calendar: CalendarData by lazy { PujoParser.calendar(read("calendar.json")) }
    val pandals: List<Pandal> by lazy { PujoParser.pandals(read("pandals.json")) }
    val zones: List<Pair<String, List<Pandal>>> by lazy { PujoParser.groupByZone(pandals) }
    val pandalById: Map<String, Pandal> by lazy { pandals.associateBy { it.id } }
    val emergency: EmergencyData by lazy { PujoParser.emergency(read("emergency.json")) }
    val metro: MetroData by lazy { PujoParser.metro(read("metro.json")) }

    companion object {
        @Volatile private var instance: PujoRepository? = null
        fun get(context: Context): PujoRepository =
            instance ?: synchronized(this) { instance ?: PujoRepository(context).also { instance = it } }
    }
}
